"""add max_apps and questions to job_posting

Revision ID: a55b93689aad
Revises: 
Create Date: 2026-01-25 22:52:13.256796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55b93689aad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_applications', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qualifying_questions', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('resume_files', schema=None) as batch_op:
        batch_op.alter_column('candidate_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_files', schema=None) as batch_op:
        batch_op.alter_column('candidate_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('qualifying_questions')
        batch_op.drop_column('max_applications')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###
